brorathon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from series.views import SerieListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^series/', include('series.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', SerieListView.as_view(), name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

series/urls.py
from django.conf.urls import url
from . import views

app_name = 'series'
urlpatterns = [
    url(r'^$', views.SerieListView.as_view(), name="list"),
    url(r'^create_serie/$', views.SerieCreateView.as_view(), name="create_serie"),
    url(r'^marathons/$', views.MarathonListView.as_view(), name="marathons"),
    url(r'^(?P<slug>[\w-]+)/$',
        views.SerieDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/validate/$', views.validate, name="validate"),
    url(r'^(?P<slug>[\w-]+)/create_marathon/$',
        views.MarathonCreateView.as_view(), name="create_marathon"),
    url(r'^(?P<slug>[\w-]+)/update/$',
        views.SerieUpdateView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/update_episode/(?P<slug2>[\w-]+)/$',
        views.EpisodeUpdateView.as_view(), name="update_episode"),
    url(r'^(?P<slug>[\w-]+)/delete_marathon/(?P<pk>[0-9]+)/$',
        views.MarathonDeleteView.as_view(), name="delete_marathon"),
    url(r'^(?P<slug>[\w-]+)/delete_serie/$',
        views.SerieDeleteView.as_view(), name="delete_serie"),
]

series/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Serie(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    synop = models.TextField(null=True, blank=True)
    thumb = models.ImageField(default='default.png')
    nb_eps = models.IntegerField()
    nb_eps_vu = models.IntegerField()
    add_by = models.ForeignKey(User)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()

        n_eps = self.episode_set.count()

        if n_eps < self.nb_eps:
            for n in range(self.nb_eps - n_eps):
                i = n_eps + n + 1
                Episode(title=self.title + " " +
                        str(i), num=i, serie=self).save()
        elif n_eps > self.nb_eps:
            for n in range(n_eps - self.nb_eps):
                self.episode_set.get(num=self.nb_eps + n + 1).delete()

    class Meta:
        verbose_name = "Serie"
        verbose_name_plural = "Series"
        ordering = ['-nb_eps_vu', 'title']


class Marathon(models.Model):
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    date = models.DateTimeField(unique=True)
    place = models.CharField(max_length=150)
    is_validate = models.BooleanField(default=False)
    add_by = models.ForeignKey(User)

    def __str__(self):
        return "{}-{}".format(self.serie.title, self.date)

    class Meta:
        verbose_name = "Marathon"
        verbose_name_plural = "Marathons"
        ordering = ['date']


class Episode(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    num = models.IntegerField()
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()

    class Meta:
        verbose_name = "Episode"
        verbose_name_plural = "Episodes"
        ordering = ['num']

series/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Serie, Marathon, Episode
import datetime


# class for SerieCreate
class SerieCreateForm(forms.ModelForm):
    class Meta:
        model = Serie
        fields = ['title', 'nb_eps', 'nb_eps_vu', 'synop', 'thumb']

    def clean(self):
        cleaned_data = super(SerieCreateForm, self).clean()
        n = cleaned_data.get("nb_eps")
        nv = cleaned_data.get("nb_eps_vu")

        if n <= 0 or nv < 0 or nv > n:
            raise forms.ValidationError("Error with nb_eps or nb_eps_vu!")
        return cleaned_data


# class for SerieUpdate
class SerieUpdateForm(forms.ModelForm):
    class Meta:
        model = Serie
        fields = ['nb_eps', 'nb_eps_vu', 'synop', 'thumb']

    def clean(self):
        cleaned_data = super(SerieUpdateForm, self).clean()
        n = cleaned_data.get("nb_eps")
        nv = cleaned_data.get("nb_eps_vu")

        if n <= 0 or nv < 0 or nv > n:
            raise forms.ValidationError("Error with nb_eps or nb_eps_vu!")
        return cleaned_data


# class for add marathon
class MarathonCreateForm(forms.ModelForm):
    class Meta:
        model = Marathon
        fields = ['date', 'place', 'is_validate']
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'date', 'id': 'date'})
        }

# class for update episode


class EpisodeUpdateForm(forms.ModelForm):
    class Meta:
        model = Episode
        fields = ['title']

series/views.py
from django.shortcuts import render,  get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Serie, Marathon, Episode
from .forms import SerieCreateForm, MarathonCreateForm, SerieUpdateForm, EpisodeUpdateForm
from .mixins import MessageMixin


class SerieListView(ListView):
    model = Serie
    template_name = 'series/index.html'
    context_object_name = 'series'


class SerieDetailView(LoginRequiredMixin, DetailView):
    model = Serie
    template_name = 'series/detail.html'


class SerieDeleteView(LoginRequiredMixin, MessageMixin, DeleteView):
    model = Serie
    success_url = reverse_lazy('home')
    success_message = 'The serie has been deleted successfully.'


class SerieCreateView(LoginRequiredMixin, MessageMixin, CreateView):
    form_class = SerieCreateForm
    template_name = 'series/create_serie.html'
    success_message = "The serie was created successfully."

    def form_valid(self, form):
        """ add the user to the instance """
        form.instance.add_by = self.request.user
        return super(SerieCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('series:detail', kwargs={'slug': self.object.slug})


class SerieUpdateView(LoginRequiredMixin, MessageMixin, UpdateView):
    model = Serie
    template_name = 'series/update.html'
    form_class = SerieUpdateForm
    success_message = "The serie was updated successfully."

    def get_success_url(self):
        return reverse_lazy('series:detail', kwargs={'slug': self.object.slug})


##############
#  MARATHON  #
##############

def validate(request, pk):
    marathon = get_object_or_404(Marathon, pk=pk)
    try:
        if marathon.is_validate:
            marathon.is_validate = False
        else:
            marathon.is_validate = True
        marathon.save()
    except (KeyError, Marathon.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


class MarathonListView(LoginRequiredMixin, ListView):
    model = Marathon
    template_name = 'series/marathons.html'
    context_object_name = 'marathons'


class MarathonDeleteView(LoginRequiredMixin, MessageMixin, DeleteView):
    model = Marathon
    success_message = 'The marathon has been deleted successfully.'

    def get_object(self):
        serie = get_object_or_404(Serie, slug=self.kwargs['slug'])
        self.kwargs.update(
            {'pk': self.kwargs['pk'], 'serie': self.kwargs['slug']})
        return super(MarathonDeleteView, self).get_object()

    def get_success_url(self):
        return reverse_lazy('series:detail', kwargs={'slug': self.kwargs.get('serie')})


class MarathonCreateView(LoginRequiredMixin, MessageMixin, CreateView):
    form_class = MarathonCreateForm
    template_name = 'series/create_marathon.html'
    success_message = "The marathon was created successfully."

    def get_context_data(self, **kwargs):
        serie = get_object_or_404(Serie, slug=self.kwargs['slug'])
        kwargs.update({'serie': serie})
        return super(MarathonCreateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        """ add the slug and user to the instance"""
        form.instance.add_by = self.request.user
        form.instance.serie = self.get_context_data()['serie']
        return super(MarathonCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('series:detail', kwargs=self.kwargs)


##############
#  EPISODES  #
##############

class EpisodeUpdateView(LoginRequiredMixin, MessageMixin, UpdateView):
    model = Episode
    template_name = 'series/update_episode.html'
    form_class = EpisodeUpdateForm
    success_message = "The episode was updated successfully."

    def get_context_data(self, **kwargs):
        serie = get_object_or_404(Serie, slug=self.kwargs['slug'])
        kwargs.update({'serie': serie, 'slug': self.kwargs['slug2']})
        return super(EpisodeUpdateView, self).get_context_data(**kwargs)

    def get_object(self):
        return get_object_or_404(Episode, slug=self.kwargs['slug2'])

    def get_success_url(self):
        return reverse_lazy('series:detail', kwargs={'slug': self.kwargs['slug']})


def add_disney():
    data = ['Snow White and the Seven Dwarfs (1937)',
            'Pinocchio (1940)',
            'Dumbo (1941)',
            'The Reluctant Dragon (1941)',
            'Bambi (1942)',
            'Victory Through Air Power (1943)',
            'Saludos Amigos (1943)',
            'The Three Caballeros (1944)',
            'Make Mine Music (1946)',
            'Song of the South (1946)',
            'Fun & Fancy Free (1947)',
            'Melody Time (1948)',
            'So Dear to My Heart (1948)',
            'The Adventures of Ichabod and Mr. Toad (1949)',
            'Cinderella (1950)',
            'Treasure Island (1950)',
            'Alice In Wonderland (1951)',
            'Story of Robin Hood and His Merrie Men, The (1952)',
            'Sword and the Rose, The (1953)',
            'Rob Roy: The Highland Rogue (1953)',
            'Peter Pan (1953)',
            '20,000 Leagues Under the Sea (1954)',
            'Littlest Outlaw, The ([1955])',
            'Lady and the Tramp (1955)',
            'Davy Crockett, King of the Wild Frontier (1955)',
            'Great Locomotive Chase, The (1956)',
            'Davy Crockett and the River Pirates (1956)',
            'Westward Ho, The Wagons! (1956)',
            'Johnny Tremain (1957)',
            'Old Yeller (1957)',
            'Light in the Forest, The (1958)',
            'Tonka (1958)',
            'Darby O\'Gill and the Little People (1959)',
            'Third Man on the Mountain (1959)',
            'Sleeping Beauty (1959)',
            'Shaggy Dog, The (1959)',
            'Ten Who Dared (1960)',
            'Swiss Family Robinson (1960)',
            'Toby Tyler (1960)',
            'Kidnapped (1960)',
            'Pollyanna (1960)',
            'Sign of Zorro, The (1960)',
            '101 Dalmatians (Animated) (1961)',
            'Babes in Toyland (1961)',
            'Parent Trap, The (1961)',
            'Greyfriars Bobby (1961)',
            'Absent-Minded Professor, The (1961)',
            'Bon Voyage! (1962)',
            'Moon Pilot (1962)',
            'Big Red (1962)',
            'Almost Angels (1962)',
            'Legend of Lobo, The (1962)',
            'In Search of Castaways (1962)',
            'Miracle of the White Stallions (1963)',
            'Savage Sam (1963)',
            'Incredible Journey, The (1963)',
            'Summer Magic (1963)',
            'Son of Flubber (1963)',
            'Sword in the Stone, The (1963)',
            'Emil and the Detectives (1964)',
            'Moon Spinners, The (1964)',
            'Three Lives of Thomasina, The (1964)',
            'Misadventures of Merlin Jones, The (1964)',
            'Tiger Walks, A (1964)',
            'Mary Poppins (1964)',
            'Those Calloways (1965)',
            'Monkey\'s Uncle, The (1965)',
            'Darn Cat, That (1965)',
            'Ugly Dachshund, The (1966)',
            'Follow Me, Boys! (1966)',
            'Fighting Prince of Donegal, The (1966)',
            'Lt. Robin Crusoe, U.S.N. (1966)',
            'Charlie, the Lonesome Cougar (1967)',
            'Gnome-Mobile, The (1967)',
            'Happiest Millionaire, The (1967)',
            'Monkeys, Go Home! (1967)',
            'Adventures of Bullwhip Griffin, The (1967)',
            'Jungle Book, The (1967)',
            'Horse in the Gray Flannel Suit, The (1968)',
            'One and Only, Genuine, Original Family Band, The (1968)',
            'Love Bug, The (1968)',
            'Blackbeard\'s Ghost (1968)',
            'Never A Dull Moment (1968)',
            'Smith! (1969)',
            'Rascal (1969)',
            'Computer Wore Tennis Shoes, The (1969)',
            'AristoCats, The (1970)',
            'Smoke (1970)',
            'Wild Country, The (1970)',
            'King of the Grizzlies (1970)',
            'Boatniks, The (1970)',
            'Barefoot Executive, The (1971)',
            'Scandalous John (1971)',
            'Bedknobs and Broomsticks (1971)',
            'Million Dollar Duck, The (1971)',
            'Now You See Him, Now You Don\'t(1972)',
            'Biscuit Eater, The (1972)',
            'Snowball Express (1972)',
            'Napoleon and Samantha (1972)',
            'Run, Cougar, Run (1972)',
            'Chandar, the Black Leopard of Ceylon (1972)',
            'World\'s Greatest Athlete, The (1973)',
            'One Little Indian (1973)',
            'Mustang (1973)',
            'Charley and the Angel (1973)',
            'Robin Hood (1973)',
            'Superdad (1973)',
            'Herbie Rides Again (1974)',
            'Bears and I, The (1974)',
            'Castaway Cowboy (1974)',
            'Island at the Top of the World, The (1974)',
            'Strongest Man in the World, The (1975)',
            'Apple Dumpling Gang, The (1975)',
            'Escape to Witch Mountain (1975)',
            'One of Our Dinosaurs is Missing (1975)',
            'Boy Who Talked to Badgers, The (1975)',
            'Ride A Wild Pony (1975)',
            'Treasure of Matecumbe (1976)',
            'Shaggy D.A., The (1976)',
            'No Deposit, No Return (1976)',
            'Freaky Friday (1976)',
            'Gus (1976)',
            'Pete\'s Dragon (1977)',
            'Herbie Goes to Monte Carlo (1977)',
            'Escape From The Dark (The Littlest Horse Thieves) (1977)',
            'Many Adventures of Winnie the Pooh, The (1977)',
            'Tale of Two Critters, A (1977)',
            'Rescuers, The (1977)',
            'Candleshoe (1977)',

templates/series/create_marathon.html
{% extends 'base_two_side_serie.html' %}

{% block right %}
    <h3>Add a New Marathon</h3>

    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}    
        {% include 'includes/_form_template.html' %}
        <div class="form=group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/series/create_serie.html
{% extends 'base.html' %}

{% block body %}
<div class="row">

    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add a New Serie</h3>

                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'includes/_form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-5">
        <div class="panel panel-default">
            <div class="panel-body">

                <h3>Some Important Notes</h3>
                <ul>
                    <li>The album logo should be a square image.</li>
                    <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                    <li>the file size should be less than 2MB.</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/series/detail.html
{% extends 'base_two_side_serie.html' %}

{% block container %}marathons-container{% endblock %}

{% block panel %}
<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>All marathons</h3>
                {% if serie.marathon_set.all %}
                    <table class="table">
                        <thread>
                            <tr>
                                <th>Date</th>
                                <th>Place</th>
                                <th>From</th>
                                <th>valid</th>
                                <th>Action</th>
                            </tr>
                        </thread>
                        <tbody>
                        {% for marathon in serie.marathon_set.all %}
                            <tr>
                                <td>{{ marathon.date }}</td>
                                <td>{{ marathon.place }}</td>
                                <td>{{ marathon.add_by }}</td>
                                <td>
                                    <a href="{% url 'series:validate' pk=marathon.id %}" class="btn-validate"> <!-- {% if marathon.is_validate %}glyphicon-star{% endif %}-->
                                        <span class="glyphicon glyphicon-star {% if not marathon.is_validate %}glyphicon-star-empty{% endif %}"></span>
                                    </a>
                                </td>
                                <td>
                                    <form action="{% url 'series:delete_marathon' slug=serie.slug pk=marathon.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                  <br>
                  <a href="{% url 'series:create_marathon' slug=serie.slug %}">
                      <button type="button" class="btn btn-success">
                          <span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Marathons
                      </button>
                  </a>
                 {% endif %}
            </div><!-- panel-body -->
        </div><!-- panel -->
    </div><!-- col -->
    <div class="col-sm-12 col-md-6">
        {% if serie.synop %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Synopsis</h3>
                    <p>{{ serie.synop|linebreaksbr }}</p>
                </div><!-- panel-body -->
            </div><!-- panel -->
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>All episodes</h3>
                <table class="table">
                    <thread>
                        <tr>
                            <th>Num</th>
                            <th>Title</th>
                            <th>Action</th>
                        </tr>
                    </thread>
                    <tbody>
                    {% for episode in serie.episode_set.all %}
                        <tr>
                            <td>{{ episode.num }}</td>
                            <td>{{ episode.title}}</td>
                            <!-- Update serie -->
                            <td>
                                <a href="{% url 'series:update_episode' slug=serie.slug slug2=episode.slug %}" class="btn btn-warning btn-sm" role="button"><span class="glyphicon glyphicon-edit"></span>&nbsp; Update</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div><!-- panel-body -->
        </div><!-- panel -->
    </div><!-- col -->
</div><!-- row -->
{% endblock %}

templates/series/index.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    {% if series %}
        {% for serie in series %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <img src="{{ serie.thumb.url }}" class="img-responsive">
                    <div class="caption">
                        <h2>{{ serie.title }}</br>
                            <small>{{ serie.nb_eps_vu }} / {{ serie.nb_eps }} seen</small>
                        </h2>
                        <h4>Added by <em>{{ serie.add_by }}</em></h4>

                        <!-- View Details -->
                        <a href="{% url "series:detail" slug=serie.slug %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        <!-- Delete Serie -->
                        <form action="{% url "series:delete_serie" slug=serie.slug %}" method="post" style="display: inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
    {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'series:create_serie' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Serie
                </button>
            </a>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/series/marathons.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid marathons-container">

    <div class="row">
        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Place</th>
                                <th>From</th>
                                <th>valid</th>
                                <th>Serie</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for marathon in marathons %}
                                <tr>
                                    <td>{{ marathon.date }}</td>
                                    <td>{{ marathon.place }}</td>
                                    <td>{{ marathon.add_by }}</td>
                                    <td>
                                        <a href="{% url 'series:validate' pk=marathon.id %}" class="btn-validate"> <!-- {% if marathon.is_validate %}glyphicon-star{% endif %}-->
                                            <span class="glyphicon glyphicon-star {% if not marathon.is_validate %}glyphicon-star-empty{% endif %}"></span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'series:detail' marathon.serie.slug %}">
                                            <img src="{{ marathon.serie.thumb.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'series:detail' marathon.serie.slug %}">{{ marathon.serie.title }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div><!-- panel-body -->
            </div><!-- panel -->

        </div><!-- col -->
    </div><!-- row -->

</div><!-- container -->
{% endblock %}

templates/series/update.html
{% extends 'base.html' %}

{% block body %}
<div class="row">

    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Update: {{serie.title}}</h3>

                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'includes/_form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-5">
        <div class="panel panel-default">
            <div class="panel-body">

                <h3>Some Important Notes</h3>
                <ul>
                    <li>The album logo should be a square image.</li>
                    <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                    <li>the file size should be less than 2MB.</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/series/update_episode.html
{% extends 'base_two_side_serie.html' %}

{% block right %}
    <h3>Update episode</h3>

    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/_form_template.html' %}
        <div class="form=group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}