accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.Signup.as_view(), name="signup"),
    url(r'^login/$', views.Login.as_view(), name="login"),
    url(r'^logout/$', views.Logout.as_view(), name="logout")
]

brorathon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from series.views import SerieListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^series/', include('series.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', SerieListView.as_view(), name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

series/urls.py
from django.conf.urls import url
from . import views

app_name = 'series'
urlpatterns = [
    url(r'^$', views.SerieListView.as_view(), name="list"),
    url(r'^create_serie/$', views.SerieCreateView.as_view(), name="create_serie"),
    url(r'^marathons/$', views.MarathonListView.as_view(), name="marathons"),
    url(r'^(?P<slug>[\w-]+)/$',
        views.SerieDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/validate/$', views.validate, name="validate"),
    url(r'^(?P<slug>[\w-]+)/create_marathon/$',
        views.MarathonCreateView.as_view(), name="create_marathon"),
    url(r'^(?P<slug>[\w-]+)/update/$',
        views.SerieUpdateView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/update_episode/(?P<slug2>[\w-]+)/$',
        views.EpisodeUpdateView.as_view(), name="update_episode"),
    url(r'^(?P<slug>[\w-]+)/delete_marathon/(?P<pk>[0-9]+)/$',
        views.MarathonDeleteView.as_view(), name="delete_marathon"),
    url(r'^(?P<slug>[\w-]+)/delete_serie/$',
        views.SerieDeleteView.as_view(), name="delete_serie"),
]

templates/includes/_form_template.html
<script>
    $(document).ready(function(){
      var date_input=$('input[name="date"]'); //our date input has the name "date"
      var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
         format: 'mm/dd/yyyy',
         container: container,
         todayHighlight: true,
         autoclose: true,
      };
      date_input.datepicker(options);
    })
</script>

{% if form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ form.non_field_errors }}</strong>
    </div>
{% endif %}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-lebel col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/includes/_navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home'%}">Brorathon</a>
        </div><!-- navbar-header -->

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home'%}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp; Series</a>
                </li>
                <li><a href="{% url 'series:marathons' %}"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Marathons</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'series:create_serie' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Serie</a></li>
                <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log out</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Log in</a></li>
                <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp; Sign in</a></li>
                {% endif %}
            </ul>
        </div><!-- collapse -->

    </div><!-- container -->
</nav>