brorathon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from series.views import SerieListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^series/', include('series.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', SerieListView.as_view(), name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

series/urls.py
from django.conf.urls import url
from . import views

app_name = 'series'
urlpatterns = [
    url(r'^$', views.SerieListView.as_view(), name="list"),
    url(r'^create_serie/$', views.SerieCreateView.as_view(), name="create_serie"),
    url(r'^marathons/$', views.MarathonListView.as_view(), name="marathons"),
    url(r'^(?P<slug>[\w-]+)/$',
        views.SerieDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/validate/$', views.validate, name="validate"),
    url(r'^(?P<slug>[\w-]+)/create_marathon/$',
        views.MarathonCreateView.as_view(), name="create_marathon"),
    url(r'^(?P<slug>[\w-]+)/update/$',
        views.SerieUpdateView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/update_episode/(?P<slug2>[\w-]+)/$',
        views.EpisodeUpdateView.as_view(), name="update_episode"),
    url(r'^(?P<slug>[\w-]+)/delete_marathon/(?P<pk>[0-9]+)/$',
        views.MarathonDeleteView.as_view(), name="delete_marathon"),
    url(r'^(?P<slug>[\w-]+)/delete_serie/$',
        views.SerieDeleteView.as_view(), name="delete_serie"),
]

templates/base.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Brorathon</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

    <!-- Custom -->
    <script rel="text/JavaScript" src="{% static 'js/main.js' %}"></script>




  </head>
  <body>
    {% include "includes/_navbar.html" %}
    <div class="container-fluid">
      {% if messages %}

          {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <strong>{{ message.tags }}!</strong> {{ message }}
            </div>

          {% endfor %}

      {% endif %}

      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

templates/base_two_side_serie.html
{% extends 'base.html' %}

{% block body %}
    <div class="container-fluid {% block container %}{% endblock %}">
        <div class="row">
            <!-- Left Serie Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if serie.thumb %}
                            <img src="{{ serie.thumb.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                        <h1>{{ serie.title }}
                            <small>{{ serie.nb_eps_vu }} / {{ serie.nb_eps }} seen</small>
                        </h1>
                        <h3>Added by <em>{{ serie.add_by }}</em></h3>
                        <!-- Update serie -->
                        <a href="{% url 'series:update' slug=serie.slug %}" class="btn btn-warning btn-sm" role="button"><span class="glyphicon glyphicon-edit"></span>&nbsp; Update</a>
                    </div><!-- panel body -->
                </div><!-- panel -->
            </div><!-- col -->

            <!-- Right Marathon Info -->
            <div class="col-sm-8 col-md-9">
              
                <ul class="nav nav-pills" style="margin-bottom: 10px">
                    <li role="presentation" class="active"><a href="{% url 'series:detail' slug=serie.slug %}">View All</a></li>
                    <li role="presentation"><a href="{% url 'series:create_marathon' slug=serie.slug %}">Add New Marathons</a></li>
                </ul>
                {% block panel %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% block right %}
                        {% endblock %}
                    </div><!-- panel-body -->
                </div><!-- panel -->
                {% endblock %}
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- container-fluid -->

{% endblock %}